apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-deployment
  labels:
    app: mock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock
  template:
    metadata:
      labels:
        app: mock
    spec:
      containers:
      - name: mock
        image: mock:1.0.0
        ports:
        - containerPort: 80
